# Generated by Django 5.0.2 on 2024-03-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_breakdown_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='question',
            new_name='questions',
        ),
    ]
